export enum ExternalApiHttpError {
  'USAGE_LIMIT_REACHED' = 'USAGE_LIMIT_REACHED',
  'NOT_FOUND' = 'NOT_FOUND',
  'INVALID_ACCESS_KEY' = 'INVALID_ACCESS_KEY',
  'INACTIVE_USER' = 'INACTIVE_USER',
  'INVALID_API_FUNCTION' = 'INVALID_API_FUNCTION',
  'FUNCTION_ACCESS_RESTRICTED' = 'FUNCITON_ACCESS_RESTRICED',
  'INVALID_FIELDS' = 'INVALID_FIELDS',
}
